### ISSUE TITLE
DRP Coupon not working on my website on mobile Device

### ISSUE THREAD

**Issue by rakeshonlybusiness** [irazasyed/wp-drp-coupon#3]
Hi
I am using DRP pluggin in my website ,it is working properly on my desktop ,but when i viewed it on a mobile device , the coupon does not show on mobile.

plz help me.

**Comment by irazasyed** [comment]
Hi, This is simply a forked copy of the original plugin to maintain online. I'm not its developer nor going to fix the issues with it. You'll have to look for an alternate or fix issues yourself.
